name: CI/CD

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build_and_test:
        strategy:
            fail-fast: false
            matrix:
                version:
                    - stable

        name: ${{ matrix.version }} - x86_64-unknown-linux-gnu
        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v3

            - name: Install ${{ matrix.version }}
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.version }}-x86_64-unknown-linux-gnu
                  profile: minimal
                  override: true

            - uses: Swatinem/rust-cache@v1

            - name: Generate Cargo.lock
              uses: actions-rs/cargo@v1
              with:
                  command: generate-lockfile

            - name: Copy .env.example to .env
              run: |
                    cp .env.example .env

            - name: Run Check
              uses: actions-rs/cargo@v1
              with:
                  command: check
                  args: --workspace

            - name: Run Format
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --all -- --check

            - name: Run Clippy
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: -- -D warnings